version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sweb-api
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=dev
    tty: true